### ISSUE TITLE
Replication fails

### ISSUE THREAD

**Issue by kirel** [kirel/detexify-data#1]
See https://issues.apache.org/jira/browse/COUCHDB-1524

**Comment by MartinThoma** [comment]
I've just asked on SO for help: http://stackoverflow.com/q/24717275/562769

**Comment by davad** [comment]
@MartinThoma Looks like your SO question got an answer. Does that solve this issue?

**Comment by MartinThoma** [comment]
@davad No (see my comment / the edit of my question)
