### ISSUE TITLE
auth issue

### ISSUE THREAD

**Issue by BogusLogin** [kirel/detexify-data#2]
Hi,
when I try to replicate the database I get an auth. error.:
"unauthorized to access or create database https://kirelabs.cloudant.com/detexify"

since I'm new to couchdb I'm not sure whether this is a problem due to my local configuration or due to the server.

**Comment by kirel** [comment]
Hey, sorry I didn't update the description yet - please contact me via Email to get a login. Having this open caused a lot of requests agains the API which became expensive.
danishkirel@gmail.com

**Comment by BogusLogin** [comment]
Thx for the quick reply, I already sent you an email. M.K.
