### ISSUE TITLE
Question: Size of the drawing grid?

### ISSUE THREAD

**Issue by EmilVogt** [kirel/detexify-data#3]
Hi, I'm playing around with your database (I want to learn a bit of Python and scikit-learn) and was asking myself on which grid size all of the examples were drawn. Was it a constant grid size? I think Detexify itself always shows 278x278 pixels, but in the data there are some with 300 pixels and more. The reason is, if the grid always changed, to compare two examples I'd have to rescale.

**Comment by kirel** [comment]
Internally I'm rescaling everything to [0,1]x[0,1] grid when I do anything
preserving aspect ration and centering. Not sure if the size changed over
time.

Am Do., 24. Sept. 2020 um 19:11 Uhr schrieb EmilVogt <
notifications@github.com>:

**Comment by EmilVogt** [comment]
Ok. Will try with rescaling. Thank you for your quick answer :)
